---

- name: "Création de l'image + container docker"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Construction des images centos"
      docker_image: path="{{playbook_dir}}/{{item}}" name="{{item}}" state=build
      with_items: [ "centos-systemd" ]

    - name: "Création du network"
      docker_network: name={{docker_network_name}}
    
    - name: "Creation des containers"
      docker_container:
        name: "{{item}}"
        hostname: "{{item}}"
        networks:
          - name: "{{docker_network_name}}"
        network_mode: "{{docker_network_name}}"
        image: "centos-systemd"
        volumes: [ "/sys/fs/cgroup:/sys/fs/cgroup:ro" ]
        state: "started"
        privileged: "yes"
        command: "/usr/lib/systemd/systemd"
      when: item != "localhost"
      with_items: "{{groups['all']}}"
