---

- name: "Création de l'image + container docker"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Construction des images centos"
      docker_image: path="{{playbook_dir}}/{{item}}" name="{{item}}" state=build
      with_items: [ "centos-systemd" ]

    - name: "Création du network"
      shell: docker network inspect {{docker_network}} || docker network create {{docker_network}}
      register: _
      changed_when: "'No such network' in _.stderr"
    
    - name: "Creation des containers"
      docker:
        name: "{{item}}"
        hostname: "{{item}}"
        net: "{{docker_network}}"
        image: "centos-systemd"
        volumes: [ "/sys/fs/cgroup:/sys/fs/cgroup:ro" ]
        state: "started"
        privileged: "yes"
        command: "/usr/lib/systemd/systemd"
      when: item != "localhost"
      with_items: "{{groups['all']}}"
