---

- name: "Installation loadbalancer"
  hosts: lb
  gather_facts: no
  handlers:
    - name: "Redémarrage haproxy"
      service: name=haproxy state=restarted enabled=yes
  tasks:
    - name: "Installation haproxy"
      yum: name=haproxy state=installed
    - name: "Préparation arborescence haproxy"
      file: path=/etc/haproxy state=directory
    - name: "Dépot fichier de configuration haproxy"
      template: src=haproxy/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
      notify: "Redémarrage haproxy"
